project_id = "gshicjqdmvlwptxogmvz"

[functions.bot-chat]
verify_jwt = false

[functions.process-client-purchase]
verify_jwt = false

[functions.test-gemini]
verify_jwt = false

[functions.test-whatsapp]
verify_jwt = false

[functions.test-smtp]
verify_jwt = false
